const introduction = [
  {
    "area": "center",
    "economy": "The City Centre is the core central activities district (CAD) of Greater Melbourne. It encompasses a number of places of significance, which include the, Federation Square, Melbourne Aquarium, Melbourne Town Hall, State Library of Victoria, State Parliament of Victoria and Supreme Court of Victoria. It is also the main terminus for the Melbourne metropolitan and Victorian regional passenger rail networks–being Flinders Street and Southern Cross stations respectively, as well as the most dense section of the Melbourne tram network.\
                  Bordering its north-east perimeter is the World Heritage-listed Royal Exhibition Building and Carlton Gardens as well as the Melbourne Museum. Just to the south are the Melbourne Convention & Exhibition Centre, Melbourne Casino, Arts Centre Melbourne, and the National Gallery of Victoria.\
                  It also serves as the main administrative centre for the City of Melbourne as well as the State Government of Victoria – the latter with the suburb of East Melbourne. Two universities have major campuses in the area: the main city campus RMIT University (city campus), and three campuses for Victoria University (City King, Queen, Flinders campuses). The Victorian College of the Arts campus of the University of Melbourne lies just to the south.",
    "arts": "Almost all the major theatres in Melbourne are located in the CBD or its fringes. Historic theatres including the Princess Theatre, Regent Theatre, Forum Theatre, Comedy Theatre, Athenaeum Theatre, Her Majesty's Theatre, and the Capitol Theatre are all located within the Hoddle Grid. The Arts Centre Melbourne (which includes the State Theatre, Hamer Hall, the Playhouse and the Fairfax Studio), and the Melbourne Recital Centre are located just to the south of the CBD, with the Sidney Myer Music Bowl in parklands to the east.\
            The Federation Square arts complex occupies a prime site on the corner of Flinders and Swanston Streets, and includes the Australian Centre for the Moving Image, the Australian art galleries of the National Gallery of Victoria, the Koorie Heritage Trust, and the Deakin Edge auditorium.\
            The CBD is home to many small independent galleries, often in the upper floors of older buildings or down laneways, and some of the most commercial galleries in Victoria are also in 'the city'.",
    "sports": "There are no sporting grounds within the CBD, but the 'shrine of sport' in Melbourne is the MCG (Melbourne Cricket Groun)) located in the adjacent parkland known as Jolimont. Both the Melbourne Cricket Club and Melbourne Football Club are based there. The Melbourne Cricket Club has a fairly exclusive membership, whilst the Melbourne Football Club, although bearing the name Melbourne, is associated by the supporters of other suburban clubs as representing the central area and perceive its supporters to represent the locality and not the entire city.[28] The Melbourne Football Club has recently made efforts to shed its suburban tag and be embraced by the whole metropolitan area.\
              ",
    "transport": "The Melbourne City Centre is the transport hub of the city.\
                  Flinders Street station is the hub for Melbourne's suburban train network and the busiest station,[30] Southern Cross station, which is the hub for regional and interstate transit located on Spencer Street, and the three underground stations of the Melbourne Underground Rail Loop–Parliament, Melbourne Central and Flagstaff stations are located on the east and north fringes.\
                  The Melbourne trams network is the largest in the world, and most lines from the suburbs run down one of the streets of the CBD, with Swanston Street hosting of six lines, making it one of the busiest tram corridors in the world. Trams also run along Flinders, Collins, Bourke, La Trobe, Spencer, Market, Elizabeth, and Spring Streets. In recent years nearly all CBD tram stops have been rebuilt as larger all-accessibility 'superstops'.\
                  The city is also well connected by bus services, with majority of buses running down Lonsdale Street, with major bus stops at Melbourne Central and Queen Victoria Village. Most bus routes service suburbs north and east of the city given the lack of train lines to these areas.\
                  Major bicycle trails lead to the CBD and a main bicycle path down Swanston Street."
  }

]